/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 14:00:00 GMT 2018
 */

package com.tv.tutorials.coolestuffvoorcheops.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.tv.tutorials.coolestuffvoorcheops.controllers.OpenIdController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OpenIdController_ESTest extends OpenIdController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OpenIdController openIdController0 = new OpenIdController();
      // Undeclared exception!
      try { 
        openIdController0.home();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.tv.tutorials.coolestuffvoorcheops.controllers.OpenIdController", e);
      }
  }
}
