/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 25 09:30:46 GMT 2018
 */

package com.cheops.candidatemanager.configuration;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cheops.candidatemanager.configuration.StorageProperties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StorageProperties_ESTest extends StorageProperties_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation((String) null);
      String string0 = storageProperties0.getLocation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation("");
      String string0 = storageProperties0.getLocation();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StorageProperties storageProperties0 = new StorageProperties();
      String string0 = storageProperties0.getLocation();
      assertEquals("upload-dir", string0);
  }
}
