/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Oct 25 12:47:41 GMT 2018
 */

package com.cheops.candidatemanager;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CandidateManagerApplication_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.cheops.candidatemanager.CandidateManagerApplication"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\THOMAS~1.VER\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\thomas.verhulst\\Documents\\workspace-sts-3.9.5.RELEASE\\coolestuffvoorcheops"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\thomas.verhulst"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thomas.Verhulst"); 
    java.lang.System.setProperty("user.timezone", "Europe/Paris"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CandidateManagerApplication_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.beans.factory.HierarchicalBeanFactory",
      "com.cheops.candidatemanager.CandidateManagerApplication",
      "org.springframework.security.access.prepost.PostInvocationAuthorizationAdvice",
      "org.springframework.security.config.annotation.ObjectPostProcessor",
      "org.springframework.security.config.annotation.web.builders.HttpSecurity",
      "org.springframework.security.access.prepost.PreInvocationAuthorizationAdvice",
      "org.springframework.security.access.method.MethodSecurityMetadataSource",
      "org.springframework.core.env.SimpleCommandLinePropertySource",
      "org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration",
      "org.springframework.boot.SpringApplication",
      "org.springframework.core.env.PropertyResolver",
      "org.springframework.boot.context.properties.EnableConfigurationProperties",
      "org.springframework.context.ApplicationEventPublisher",
      "org.springframework.security.config.annotation.SecurityConfigurer",
      "org.springframework.security.access.intercept.aspectj.AspectJMethodSecurityInterceptor",
      "org.springframework.security.access.prepost.PrePostInvocationAttributeFactory",
      "org.springframework.core.io.Resource",
      "org.springframework.core.io.ResourceLoader",
      "org.springframework.security.access.AccessDecisionManager",
      "org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor",
      "org.springframework.security.config.annotation.SecurityConfigurerAdapter",
      "org.springframework.security.config.annotation.SecurityBuilder",
      "org.springframework.core.env.CompositePropertySource",
      "org.springframework.security.access.intercept.AbstractSecurityInterceptor",
      "com.cheops.candidatemanager.services.IStorageService",
      "org.springframework.core.env.Environment",
      "org.springframework.core.env.MapPropertySource",
      "org.springframework.security.oauth2.config.annotation.web.configurers.ResourceServerSecurityConfigurer",
      "com.cheops.candidatemanager.CandidateManagerApplication$GlobalSecurityConfiguration",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.aop.framework.AopInfrastructureBean",
      "org.springframework.security.config.annotation.web.HttpSecurityBuilder",
      "org.springframework.beans.factory.ListableBeanFactory",
      "org.springframework.core.env.CommandLinePropertySource",
      "org.springframework.boot.ApplicationArguments",
      "org.springframework.core.env.PropertySource",
      "org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter",
      "org.springframework.core.env.ConfigurablePropertyResolver",
      "org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurer",
      "org.springframework.beans.factory.Aware",
      "org.springframework.core.env.EnumerablePropertySource",
      "com.cheops.candidatemanager.CandidateManagerApplication$1",
      "org.springframework.beans.factory.InitializingBean",
      "org.springframework.security.access.intercept.AfterInvocationManager",
      "org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder",
      "org.aopalliance.intercept.Interceptor",
      "org.springframework.core.env.ConfigurableEnvironment",
      "org.springframework.security.access.expression.method.MethodSecurityExpressionHandler",
      "org.springframework.core.env.EnvironmentCapable",
      "org.springframework.context.annotation.ImportAware",
      "org.aopalliance.aop.Advice",
      "org.springframework.boot.CommandLineRunner",
      "org.springframework.security.access.expression.SecurityExpressionHandler",
      "com.cheops.candidatemanager.configuration.StorageProperties",
      "org.springframework.context.MessageSource",
      "org.springframework.context.ApplicationEventPublisherAware",
      "org.springframework.boot.autoconfigure.SpringBootApplication",
      "org.springframework.boot.autoconfigure.EnableAutoConfiguration",
      "org.springframework.context.MessageSourceAware",
      "org.springframework.boot.ExitCodeEvent",
      "org.springframework.context.annotation.Import",
      "org.springframework.context.ApplicationContext",
      "org.springframework.beans.factory.SmartInitializingSingleton",
      "org.springframework.context.annotation.ComponentScan",
      "org.springframework.security.access.SecurityMetadataSource",
      "org.springframework.context.ApplicationEvent",
      "org.aopalliance.intercept.MethodInterceptor",
      "org.springframework.boot.SpringBootConfiguration",
      "org.springframework.beans.factory.BeanFactory",
      "org.springframework.web.multipart.MultipartFile",
      "org.springframework.security.config.annotation.AbstractSecurityBuilder",
      "org.springframework.core.io.support.ResourcePatternResolver",
      "org.springframework.security.authentication.AuthenticationEventPublisher"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.cheops.candidatemanager.services.IStorageService", false, CandidateManagerApplication_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CandidateManagerApplication_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.cheops.candidatemanager.CandidateManagerApplication",
      "org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter",
      "com.cheops.candidatemanager.CandidateManagerApplication$1",
      "org.springframework.beans.factory.annotation.Autowire",
      "org.springframework.context.annotation.AdviceMode",
      "org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration",
      "org.springframework.boot.SpringApplication",
      "org.springframework.security.access.method.AbstractMethodSecurityMetadataSource",
      "org.springframework.security.access.method.AbstractFallbackMethodSecurityMetadataSource",
      "org.springframework.security.access.annotation.Jsr250MethodSecurityMetadataSource"
    );
  }
}
