/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 25 09:24:16 GMT 2018
 */

package com.cheops.candidatemanager.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cheops.candidatemanager.configuration.StorageProperties;
import com.cheops.candidatemanager.services.impl.StorageService;
import java.io.IOError;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.util.stream.Stream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StorageService_ESTest extends StorageService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn((InputStream) null).when(multipartFile0).getInputStream();
      doReturn("iilh").when(multipartFile0).getOriginalFilename();
      doReturn(false).when(multipartFile0).isEmpty();
      // Undeclared exception!
      try { 
        storageService0.store(multipartFile0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation("=9MQauKU");
      storageService0.FileSystemStorageService(storageProperties0);
      storageService0.deleteAll();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      Stream<Path> stream0 = storageService0.loadAll();
      assertNotNull(stream0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      Path path0 = storageService0.load("iilh");
      assertNotNull(path0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      PipedInputStream pipedInputStream0 = new PipedInputStream(807);
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn(pipedInputStream0).when(multipartFile0).getInputStream();
      doReturn("?(6r").when(multipartFile0).getOriginalFilename();
      doReturn(false).when(multipartFile0).isEmpty();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.store(multipartFile0);
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(multipartFile0).getOriginalFilename();
      doReturn(false).when(multipartFile0).isEmpty();
      // Undeclared exception!
      try { 
        storageService0.store(multipartFile0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.loadAsResource("Zhyj8qZIa)\">G$Z7");
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.loadAsResource("K:");
        fail("Expecting exception: IOError");
      
      } catch(IOError e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation("org.sprin6framework.http.server.Peactive.ContextPathCompositeHandler");
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.loadAll();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to read stored files
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.load("N=*Tnp:~V");
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation("GY|[&Te~Zj(W");
      // Undeclared exception!
      try { 
        storageService0.FileSystemStorageService(storageProperties0);
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation((String) null);
      // Undeclared exception!
      try { 
        storageService0.FileSystemStorageService(storageProperties0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageProperties0.setLocation("");
      storageService0.FileSystemStorageService(storageProperties0);
      Resource resource0 = storageService0.loadAsResource("");
      assertEquals("", resource0.getFilename());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.load("iilh");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn("..").when(multipartFile0).getOriginalFilename();
      doReturn(false).when(multipartFile0).isEmpty();
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.store(multipartFile0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot store file with relative path outside current directory ..
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn("_").when(multipartFile0).getOriginalFilename();
      doReturn(true).when(multipartFile0).isEmpty();
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.store(multipartFile0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to store empty file _
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.deleteAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.init();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.file.Files", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.loadAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.file.Files", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      StorageProperties storageProperties0 = new StorageProperties();
      storageService0.FileSystemStorageService(storageProperties0);
      // Undeclared exception!
      try { 
        storageService0.loadAsResource("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not read file: 
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StorageService storageService0 = new StorageService();
      // Undeclared exception!
      try { 
        storageService0.loadAsResource("K:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cheops.candidatemanager.services.impl.StorageService", e);
      }
  }
}
