/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 14:00:39 GMT 2018
 */

package com.cheops.candidatemanager.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cheops.candidatemanager.models.Address;
import com.cheops.candidatemanager.repositories.AddressRepository;
import com.cheops.candidatemanager.services.impl.AddressService;
import java.time.chrono.ChronoLocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddressService_ESTest extends AddressService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      HashSet<Address> hashSet0 = new HashSet<Address>(0, 4036.21F);
      Address address0 = new Address("O\"b(2I~9", "Nc4^b4#-F0_+tir X4<", "Nc4^b4#-F0_+tir X4<", "", "", "");
      hashSet0.add(address0);
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn(hashSet0).when(addressRepository0).findAll();
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      List<Address> list0 = addressService0.getAllAdresses();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      // Undeclared exception!
      try { 
        addressService0.updateAddress((Address) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AddressService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      Object object0 = new Object();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn(object0).when(addressRepository0).save(nullable(java.lang.Object.class));
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      // Undeclared exception!
      try { 
        addressService0.updateAddress((Address) null);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to Address
         //
         verifyException("AddressRepository$MockitoMock$258995563", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Optional<Object>) null).when(addressRepository0).findById(anyInt());
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      // Undeclared exception!
      try { 
        addressService0.getAddressById((-200));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AddressService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Optional) null).when(addressRepository0).findById(anyInt());
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      // Undeclared exception!
      try { 
        addressService0.deleteAdress(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AddressService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      // Undeclared exception!
      try { 
        addressService0.addAddress((Address) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AddressService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn((ChronoLocalDate) null, "").when(addressRepository0).save(nullable(java.lang.Object.class));
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      addressService0.addAddress((Address) null);
      // Undeclared exception!
      try { 
        addressService0.addAddress((Address) null);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to Address
         //
         verifyException("AddressRepository$MockitoMock$258995563", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(addressRepository0).save(nullable(java.lang.Object.class));
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      addressService0.updateAddress((Address) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AddressService addressService0 = new AddressService();
      AddressRepository addressRepository0 = mock(AddressRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Iterable) null).when(addressRepository0).findAll();
      Injector.inject(addressService0, (Class<?>) AddressService.class, "addressRepository", (Object) addressRepository0);
      Injector.validateBean(addressService0, (Class<?>) AddressService.class);
      // Undeclared exception!
      try { 
        addressService0.getAllAdresses();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AddressService", e);
      }
  }
}
