/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 25 09:26:37 GMT 2018
 */

package com.cheops.candidatemanager.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cheops.candidatemanager.exceptions.StorageFileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StorageFileNotFoundException_ESTest extends StorageFileNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StorageFileNotFoundException storageFileNotFoundException0 = new StorageFileNotFoundException("#");
      StorageFileNotFoundException storageFileNotFoundException1 = new StorageFileNotFoundException("#", storageFileNotFoundException0);
      assertFalse(storageFileNotFoundException1.equals((Object)storageFileNotFoundException0));
  }
}
