/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 25 12:50:24 GMT 2018
 */

package com.cheops.candidatemanager.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cheops.candidatemanager.controllers.SignInWidgetConfigController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SignInWidgetConfigController_ESTest extends SignInWidgetConfigController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SignInWidgetConfigController.WidgetConfig signInWidgetConfigController_WidgetConfig0 = new SignInWidgetConfigController.WidgetConfig("]3+>*", "com.cheops.candidatemanager.controllers.SignInWidgetConfigController");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SignInWidgetConfigController signInWidgetConfigController0 = null;
      try {
        signInWidgetConfigController0 = new SignInWidgetConfigController("", (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Property 'okta.oauth2.issuer' is required.
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SignInWidgetConfigController signInWidgetConfigController0 = new SignInWidgetConfigController("", "");
      SignInWidgetConfigController.WidgetConfig signInWidgetConfigController_WidgetConfig0 = signInWidgetConfigController0.getWidgetConfig();
      assertNotNull(signInWidgetConfigController_WidgetConfig0);
  }
}
