/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 13:58:16 GMT 2018
 */

package com.cheops.candidatemanage.models;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cheops.candidatemanager.models.MyUploadForm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.web.multipart.MultipartFile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyUploadForm_ESTest extends MyUploadForm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      MultipartFile[] multipartFileArray0 = new MultipartFile[4];
      myUploadForm0.setFileDatas(multipartFileArray0);
      MultipartFile[] multipartFileArray1 = myUploadForm0.getFileDatas();
      assertEquals(4, multipartFileArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      MultipartFile[] multipartFileArray0 = new MultipartFile[0];
      myUploadForm0.setFileDatas(multipartFileArray0);
      MultipartFile[] multipartFileArray1 = myUploadForm0.getFileDatas();
      assertEquals(0, multipartFileArray1.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      myUploadForm0.setDescription("copied");
      String string0 = myUploadForm0.getDescription();
      assertEquals("copied", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      MultipartFile[] multipartFileArray0 = myUploadForm0.getFileDatas();
      assertNull(multipartFileArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      String string0 = myUploadForm0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MyUploadForm myUploadForm0 = new MyUploadForm();
      myUploadForm0.setDescription("");
      String string0 = myUploadForm0.getDescription();
      assertEquals("", string0);
  }
}
