///*
// * This file was automatically generated by EvoSuite
// * Thu Oct 25 12:52:51 GMT 2018
// */
//
//package com.cheops.candidatemanager.models;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//import com.cheops.candidatemanager.models.Update;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.runner.RunWith;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class Update_ESTest extends Update_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test0()  throws Throwable  {
//      Update update0 = new Update(true);
//      boolean boolean0 = update0.isUpdate();
//      assertTrue(boolean0);
//  }
//
//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      Update update0 = new Update(true);
//      update0.setCurrentSalaryPackage0OrProposedSalarypackage1(1194);
//      int int0 = update0.getCurrentSalaryPackage0OrProposedSalarypackage1();
//      assertEquals(1194, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test2()  throws Throwable  {
//      Update update0 = new Update();
//      update0.setCurrentSalaryPackage0OrProposedSalarypackage1((-670));
//      int int0 = update0.getCurrentSalaryPackage0OrProposedSalarypackage1();
//      assertEquals((-670), int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test3()  throws Throwable  {
//      Update update0 = new Update();
//      update0.setUpdate(true);
//      assertTrue(update0.isUpdate());
//  }
//
//  @Test(timeout = 4000)
//  public void test4()  throws Throwable  {
//      Update update0 = new Update();
//      int int0 = update0.getCurrentSalaryPackage0OrProposedSalarypackage1();
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test5()  throws Throwable  {
//      Update update0 = new Update();
//      boolean boolean0 = update0.isUpdate();
//      assertFalse(boolean0);
//  }
//}
