/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 25 12:49:55 GMT 2018
 */

package com.cheops.candidatemanager.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.cheops.candidatemanager.controllers.LoginController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.ui.Model;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoginController_ESTest extends LoginController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoginController loginController0 = new LoginController();
      String string0 = loginController0.loginView();
      assertEquals("login", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoginController loginController0 = new LoginController();
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      String string0 = loginController0.login(model0);
      assertEquals("home", string0);
  }
}
