/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Oct 16 13:56:07 GMT 2018
 */

package com.tv.tutorials.coolestuffvoorcheops.controllers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ApplicationProcessController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.tv.tutorials.coolestuffvoorcheops.controllers.ApplicationProcessController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\THOMAS~1.VER\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\thomas.verhulst\\Documents\\workspace-sts-3.9.5.RELEASE\\coolestuffvoorcheops"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\thomas.verhulst"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thomas.Verhulst"); 
    java.lang.System.setProperty("user.timezone", "Europe/Paris"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ApplicationProcessController_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.validation.Errors",
      "com.tv.tutorials.coolestuffvoorcheops.models.Candidate",
      "com.tv.tutorials.coolestuffvoorcheops.services.IApplicationProcessService",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.beans.PropertyEditorRegistry",
      "org.springframework.validation.BindingResult",
      "com.tv.tutorials.coolestuffvoorcheops.models.Address",
      "org.springframework.stereotype.Controller",
      "org.springframework.ui.Model",
      "org.springframework.context.support.DefaultMessageSourceResolvable",
      "org.springframework.validation.ObjectError",
      "com.tv.tutorials.coolestuffvoorcheops.models.CandidateSearchResolver",
      "org.springframework.stereotype.Service",
      "org.springframework.stereotype.Indexed",
      "org.springframework.lang.Nullable",
      "org.springframework.context.MessageSourceResolvable",
      "com.tv.tutorials.coolestuffvoorcheops.controllers.ApplicationProcessController",
      "org.springframework.web.servlet.mvc.support.RedirectAttributes",
      "com.tv.tutorials.coolestuffvoorcheops.services.impl.ApplicationProcessService",
      "com.tv.tutorials.coolestuffvoorcheops.models.ApplicationProcess",
      "org.springframework.validation.FieldError",
      "com.tv.tutorials.coolestuffvoorcheops.services.impl.CandidateService",
      "com.tv.tutorials.coolestuffvoorcheops.services.ICandidateService",
      "org.springframework.stereotype.Component",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.web.multipart.MultipartFile"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.tv.tutorials.coolestuffvoorcheops.models.ApplicationProcess", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.tv.tutorials.coolestuffvoorcheops.models.Candidate", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.tv.tutorials.coolestuffvoorcheops.services.impl.ApplicationProcessService", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.tv.tutorials.coolestuffvoorcheops.services.impl.CandidateService", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.ui.Model", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.validation.BindingResult", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.web.servlet.mvc.support.RedirectAttributes", false, ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ApplicationProcessController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.tv.tutorials.coolestuffvoorcheops.controllers.ApplicationProcessController",
      "org.springframework.web.bind.annotation.RequestMethod",
      "com.tv.tutorials.coolestuffvoorcheops.services.impl.ApplicationProcessService",
      "com.tv.tutorials.coolestuffvoorcheops.services.impl.CandidateService",
      "com.tv.tutorials.coolestuffvoorcheops.models.ApplicationProcess",
      "org.springframework.validation.BindingResult",
      "com.tv.tutorials.coolestuffvoorcheops.models.Candidate"
    );
  }
}
