/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 14:01:23 GMT 2018
 */

package com.cheops.candidatemanager.controllers;

import org.junit.Test;
import com.cheops.candidatemanager.controllers.RoleController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RoleController_ESTest extends RoleController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RoleController roleController0 = new RoleController();
  }
}
