/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 13:57:23 GMT 2018
 */

package com.cheops.candidatemanager.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cheops.candidatemanager.controllers.SignInWidgetConfigController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SignInWidgetConfigController_ESTest extends SignInWidgetConfigController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SignInWidgetConfigController.WidgetConfig signInWidgetConfigController_WidgetConfig0 = new SignInWidgetConfigController.WidgetConfig("Property 'okta.oauth2.clientId' is required.", "");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SignInWidgetConfigController signInWidgetConfigController0 = null;
      try {
        signInWidgetConfigController0 = new SignInWidgetConfigController("GrJXDs8p7hNkgKz", (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Property 'okta.oauth2.issuer' is required.
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SignInWidgetConfigController signInWidgetConfigController0 = new SignInWidgetConfigController("*!p\"^8ZKc", "*!p\"^8ZKc");
      SignInWidgetConfigController.WidgetConfig signInWidgetConfigController_WidgetConfig0 = signInWidgetConfigController0.getWidgetConfig();
      assertNotNull(signInWidgetConfigController_WidgetConfig0);
  }
}
