/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 14:02:15 GMT 2018
 */

package com.cheops.candidatemanager.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cheops.candidatemanager.controllers.TestController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestController_ESTest extends TestController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestController testController0 = new TestController();
      String string0 = testController0.showtest();
      assertEquals("test", string0);
  }
}
